[build]
  publish = "."
  command = ""

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"