# netlify.toml — functions + Node 18 + headers (cache bust)
[build]
command = ""
publish = "."

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[build.environment]
NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/app.v901.js"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/watch.v901.js"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
